
#site settings
title: Nephrite21
email: gsm4526@naver.com
url: https://Nephrite21.github.io

githuburl: https://github.com/Nephrite21
blogurl: https://nephrite21.tistory.com/

#about page introduction
introduction:  
  greeting: Hello!, I'm Nephrite21!
  introductionAboutMe:  I usually play and make games!<br>My dream is to create a game that allows people to fully immerse themselves, and find happiness in it.<br>To achive it, I design and develope games with Unity and Unreal Engine<br> Learn more about me in My blog below



# 1 icon = 1 detail
# unity-csharp, unreal-cpp, html-css-js
# if you add more component, change var indexNum at "about.js" to Number of contents
skillImageIcon:  
  - src: /assets/img/unity-csharp.png
  - src: /assets/img/unreal-cpp.png
  - src: /assets/img/html-css-js.png

skillDetail:
  - skillName: Unity - C#
    skillDetail: 
      - title: asd
        link: https://nephrite21.github.io/
        description: asd is a goood website
  - skillName: Unreal - C++
    skillDetail: 
    previousWork:
      - title: zxc
        link: https://nephrite21.github.io/
        description: zxc is a goood website
    skillDetail: asd
    previousWork:
      - title: Nephrite21.github.io
        link: https://nephrite21.github.io/
        description: The site you are viewing right now is built by myself with HTML/CSS/JS with jquery,bootstrap and Jekyll etc.

Works:
  - img: /assets/img/game.png
    link: https://nephrite21.github.io/
  - img: /assets/img/game.png
    link: https://nephrite21.github.io/
  - img: /assets/img/game.png
    link: https://nephrite21.github.io/
  - img: /assets/img/game.png
    link: https://nephrite21.github.io/